#! /bin/bash

#-------------------------------------------
# File generated 2021-08-11 11:30:31.558164
#-------------------------------------------

#SBATCH --account=nn4654k
#SBATCH --job-name=59_pbe_
#SBATCH --output=59_pbe_.log
#SBATCH --error=59_pbe_.err
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=6
#SBATCH --time=12:00:00
#SBATCH --mem=140GB
#SBATCH --mail-type=NONE
#SBATCH --partition=normal

module load Python/3.8.2-GCCcore-9.3.0
export OMP_NUM_THREADS=6

set -o errexit
set -o nounset

cp 59_pbe_.inp $SCRATCH

cd $SCRATCH
/cluster/home/ambr/mrchem_master/install-1.0.1/bin/mrchem --launcher 'srun' 59_pbe_

savefile 59_pbe_.out
savefile 59_pbe_.json

mkdir -p /cluster/projects/nn4654k/ambr/MWorbitals_${SLURM_JOBID}
cp orbitals/* /cluster/projects/nn4654k/ambr/MWorbitals_${SLURM_JOBID}/
echo /cluster/projects/nn4654k/ambr/MWorbitals_${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/59_pbe_.orbitals

mkdir -p /cluster/projects/nn4654k/ambr/MWcheckpoints_${SLURM_JOBID}
cp checkpoint/* /cluster/projects/nn4654k/ambr/MWcheckpoints_${SLURM_JOBID}/
echo /cluster/projects/nn4654k/ambr/MWcheckpoints_${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/59_pbe_.checkpoint

exit 0
