#! /bin/bash

#-------------------------------------------
# File generated 2021-07-14 15:06:41.553819
#-------------------------------------------

#SBATCH --account=nn4654k
#SBATCH --job-name=68_b3lyp-g_
#SBATCH --output=68_b3lyp-g_.log
#SBATCH --error=68_b3lyp-g_.err
#SBATCH --ntasks=10
#SBATCH --cpus-per-task=10
#SBATCH --time=50:00:00
#SBATCH --mem=60GB
#SBATCH --mail-type=NONE
#SBATCH --partition=normal

module load Python/3.8.2-GCCcore-9.3.0
export OMP_NUM_THREADS=10

set -o errexit
set -o nounset

cp 68_b3lyp-g_.inp $SCRATCH

cd $SCRATCH
/cluster/home/ambr/mrchem_master/install-1.0.1/bin/mrchem --launcher 'srun' 68_b3lyp-g_

savefile 68_b3lyp-g_.out
savefile 68_b3lyp-g_.json

mkdir -p /cluster/projects/nn4654k/ambr/MWorbitals_${SLURM_JOBID}
cp orbitals/* /cluster/projects/nn4654k/ambr/MWorbitals_${SLURM_JOBID}/
echo /cluster/projects/nn4654k/ambr/MWorbitals_${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/68_b3lyp-g_.orbitals

mkdir -p /cluster/projects/nn4654k/ambr/MWcheckpoints_${SLURM_JOBID}
cp checkpoint/* /cluster/projects/nn4654k/ambr/MWcheckpoints_${SLURM_JOBID}/
echo /cluster/projects/nn4654k/ambr/MWcheckpoints_${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/68_b3lyp-g_.checkpoint

exit 0
